/**
 * copy-engine.cjs - Copy Client Engine to Functions
 * 
 * Copies the deterministic engine modules from `src/engine` to
 * `functions/src/shared` to ensure server uses identical logic.
 * 
 * Run: npm run copy-engine (from functions directory)
 * Or:  node scripts/copy-engine.cjs (from project root)
 * 
 * @version 3.0.0
 */

const fs = require('fs');
const path = require('path');

// Paths
const projectRoot = path.resolve(__dirname, '..');
const srcEngine = path.join(projectRoot, 'src', 'engine');
const destShared = path.join(projectRoot, 'functions', 'src', 'shared');

// Files to copy (only deterministic modules)
const filesToCopy = [
    'rng.js',
    'fixedPoint.js',
    'version.js',
    'priceCalculator.js',
    'marketState.js'
];

// Constants to copy
const constantsToCopy = [
    'src/constants/stocks.js',
    'src/constants/trading.js'
];

/**
 * Convert ES Module syntax to CommonJS for Node.js
 */
function convertToCommonJS(content, filename) {
    let converted = content;

    // Convert export const/function to module.exports
    converted = converted.replace(/^export const (\w+)/gm, 'const $1');
    converted = converted.replace(/^export function (\w+)/gm, 'function $1');
    converted = converted.replace(/^export \{[^}]+\}/gm, '');

    // Remove import statements and replace with require
    converted = converted.replace(
        /import \{([^}]+)\} from ['"]([^'"]+)['"]/g,
        (match, imports, modulePath) => {
            const moduleFile = modulePath.replace('../', './').replace('./', '');
            return `const {${imports}} = require('./${moduleFile}')`;
        }
    );

    // Add exports at the end
    const exportMatches = content.match(/export (?:const|function) (\w+)/g);
    if (exportMatches) {
        const exportNames = exportMatches.map(m => m.split(' ').pop());
        converted += `\n\nmodule.exports = { ${exportNames.join(', ')} };\n`;
    }

    return converted;
}

/**
 * Main copy function
 */
function copyEngineFiles() {
    console.log('🚀 Copying engine files to functions/src/shared...\n');

    // Create destination directory
    if (!fs.existsSync(destShared)) {
        fs.mkdirSync(destShared, { recursive: true });
        console.log(`📁 Created: ${destShared}`);
    }

    // Copy and convert engine files
    for (const file of filesToCopy) {
        const srcPath = path.join(srcEngine, file);
        const destPath = path.join(destShared, file.replace('.js', '.ts'));

        if (!fs.existsSync(srcPath)) {
            console.log(`⚠️  Skipped (not found): ${file}`);
            continue;
        }

        const content = fs.readFileSync(srcPath, 'utf8');

        // For TypeScript, we just copy with minimal modifications
        let tsContent = content;

        // Add TypeScript type annotations where needed
        tsContent = `// @ts-nocheck\n/**\n * AUTO-GENERATED - Do not edit directly!\n * Source: src/engine/${file}\n * Generated by: scripts/copy-engine.cjs\n */\n\n` + tsContent;

        // Convert .js imports to relative
        tsContent = tsContent.replace(/from ['"]\.\.\/constants['"]/g, "from './constants'");
        tsContent = tsContent.replace(/from ['"]\.\/(\w+)['"]/g, "from './$1'");

        fs.writeFileSync(destPath, tsContent);
        console.log(`✅ Copied: ${file} → shared/${file.replace('.js', '.ts')}`);
    }

    // Create a combined constants file
    console.log('\n📦 Creating shared constants...');

    let constantsContent = `// @ts-nocheck\n/**\n * AUTO-GENERATED - Combined constants for server\n */\n\n`;

    for (const constFile of constantsToCopy) {
        const srcPath = path.join(projectRoot, constFile);
        if (fs.existsSync(srcPath)) {
            const content = fs.readFileSync(srcPath, 'utf8');
            // Extract and append exports
            constantsContent += `// From ${constFile}\n`;
            constantsContent += content.replace(/^import.*$/gm, '').trim();
            constantsContent += '\n\n';
            console.log(`  ✅ Included: ${constFile}`);
        }
    }

    fs.writeFileSync(path.join(destShared, 'constants.ts'), constantsContent);

    // Create index.ts for shared module
    const indexContent = `// @ts-nocheck
/**
 * Shared Engine Modules
 * AUTO-GENERATED - Do not edit directly!
 */

export * from './rng';
export * from './fixedPoint';
export * from './version';
export * from './priceCalculator';
export * from './marketState';
export * from './constants';
`;

    fs.writeFileSync(path.join(destShared, 'index.ts'), indexContent);

    console.log('\n✨ Engine copy complete!\n');
    console.log('Next steps:');
    console.log('  1. cd functions');
    console.log('  2. npm install');
    console.log('  3. npm run build');
}

// Run if executed directly
if (require.main === module) {
    copyEngineFiles();
}

module.exports = { copyEngineFiles };
